version: '3'
services:
#  client-api:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#    image: rest/client
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    environment:
#      - ADD_OPT=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
#      - PROFILE=dev
#    links:
#      - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pg_volume:/var/lib/postgresql/data