apiVersion: apps/v1
kind: Deployment
metadata:
  name: torra-tudo-gateway-deployment
  labels:
   app: torra-tudo-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: torra-tudo-gateway-deployment
  template:
    metadata:
      labels:
        app: torra-tudo-gateway-deployment
    spec:
      containers:
        - name: torra-tudo-gateway
          image: 'juanpablooo/torra-tudo-gateway:VERSION_IMAGE_TO_BE_REPLACED'
          ports:
#            - port: 8082
            - containerPort:  8080
          env:
            - name: DISCOVERY_URL
              valueFrom:
                configMapKeyRef:
                  name: discovery-configmap
                  key: discovery-url

---
apiVersion: v1
kind: Service
metadata:
  name: torra-tudo-gateway-service
spec:
  selector:
    app: torra-tudo-gateway-deployment
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8088 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
#      nodePort: 30001
#  type: NodePort

#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: springboot-v1
#  namespace: default
#spec:
#  maxReplicas: 3
#  minReplicas: 1
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: springboot-v1
#  targetCPUUtilizationPercentage: 70