apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
#   labels:
#     app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: torra-client
          image: 'juanpablooo/torra-client:1.0.0'
          ports:
            #            - port: 8082
            - containerPort:  8083