version: '3.1'

services:
  torra:
    build:
      context: ./
      dockerfile: Dockerfile
    image: custom-jdk-11
    ports:
      - "8082:8082"
    environment:
      - ADDITIONAL_OPT=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev