pipeline {
    agent {
        image "maven:3.6.0-jdk-13"
        label "docker"
    }

    stages {
        stage("Build") {
            echo "test"
            sh "mvn -version"
            sh "mvn clean install"
        }

    }

}