def project = "discovery"
def docker_hub_profile = "juanpablooo"
def branch = "develop"
def tag = env.BUILD_ID

pipeline {
    agent any
    tools {
        maven "maven"
    }
    stages {
        stage("Git clone") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: "*/${branch}"]], extensions: [], userRemoteConfigs: [[url: 'https://github.com/JuanPablooo/torra-tudo']]])
            }
        }
        stage("Maven Test") {
            steps {
                sh "mvn test -f ${project} -U"
            }
        }

        stage("Maven Build") {
            steps {
                sh "mvn clean install -Dmaven.test.skip=true -f ${project} -U"
            }

        }

       stage("Docker Build") {
            steps{
                script {
                    sh "docker build -t ${project} ./${project}/"
                    sh "docker tag ${project} ${docker_hub_profile}/${project}:${tag}"
                    sh "echo imagename: ${docker_hub_profile}/${project}:${tag}"
                }
            }
        }
       stage("Docker Push") {
            steps{
                script {
                    withCredentials([string(credentialsId: 'dockerhubpwp', variable: 'dockerhubpwp')]) {
                        sh "docker login -u ${docker_hub_profile} -p ${dockerhubpwp}"
                        sh "docker push ${docker_hub_profile}/${project}:${tag}"
                    }
                }
            }
        }
        stage("K8S Deploy") {
            steps {
                script{
                    sh "pwd ls"
                    dir("./${project}/k8s") {
                        sh "echo replacing tag [ ${tag} ] image ..."
                        sh "sed -i 's,VERSION_IMAGE_TO_BE_REPLACED,${tag},' ./deployment.yaml"
                        kubernetesDeploy (configs: 'deployment.yaml', kubeconfigId: 'k8sconfigpwd')
                    }

                }
            }
        }

    }

}