apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
#   labels:
#     app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: torra-product
          image: 'juanpablooo/torra-product:1.0.0'
          ports:
#            - port: 8082
            - containerPort:  8082